/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;
import java.util.Random;
/**
 *
 * @author james
 */
public class formSelector extends javax.swing.JDialog 
{
    String forms[] = new String [] {"Basic","Il Jang", "taegeuk 1", "Ee Jang", "taegeuk 2", "Sam Jang", "taegeuk 3", "sah Jang", "taegeuk 4", "Oh Jang", "taegeuk 5", "Yuk Jang", "taegeuk 6", "Chil Jang", "taegeuk 7", "Pal Jang", "taegeuk 8" };
    Integer previousNumber = -1;
    Random rand = new Random();
    /**
     * Creates new form formSelector
     */
    public formSelector(main inParent) {
        super(inParent, true);
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        formCombo = new javax.swing.JComboBox<>();
        formLabel = new javax.swing.JLabel();
        randFormButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Current Form:");

        formCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Il Jang - Taeguek 1", "Ee Jang - Taeguek 2", "Sam Jang - Taeguek 3", "Sah Jang - Taeguek 4", "Oh Jang - Taeguek 5", "Yuk Jang - Taeguek 6", "Chil Jang - Taeguek 7", "Pal Jang - Taeguek 8" }));

        formLabel.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        formLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formLabel.setBorder(null);

        randFormButton.setText("Random Form");
        randFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randFormButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(formLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(randFormButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(formCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(formCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(randFormButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(formLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int getRandom (Integer numIn)
    {
        int newRandomNumber = -2;
        do 
            {
                newRandomNumber = genRandNum(numIn);
                System.out.println("new random: " + newRandomNumber + ", previous random: " + previousNumber);
            } while (previousNumber == newRandomNumber);
        previousNumber = newRandomNumber;
        return newRandomNumber;
    }
    
    private void randFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randFormButtonActionPerformed
        int maxNum = 0;

        if (formCombo.getSelectedItem().equals("Il Jang - Taeguek 1"))
        {
            formLabel.setText(forms[getRandom(3)]);
        }
        else if (formCombo.getSelectedItem().equals("Ee Jang - Taeguek 2"))
        {
            formLabel.setText(forms[getRandom(5)]);
        }
        else if (formCombo.getSelectedItem().equals("Sam Jang - Taeguek 3"))
        {
            formLabel.setText(forms[getRandom(7)]);
        }
        else if (formCombo.getSelectedItem().equals("Sah Jang - Taeguek 4"))
        {
            formLabel.setText(forms[getRandom(9)]);
        }
        else if (formCombo.getSelectedItem().equals("Oh Jang - Taeguek 5"))
        {
            formLabel.setText(forms[getRandom(11)]);
        }
        else if (formCombo.getSelectedItem().equals("Yuk Jang - Taeguek 6"))
        {
            formLabel.setText(forms[getRandom(13)]);
        }
        else if (formCombo.getSelectedItem().equals("Chil Jang - Taeguek 7"))
        {
            formLabel.setText(forms[getRandom(15)]);
        }
        else if (formCombo.getSelectedItem().equals("Pal Jang - Taeguek 8"))
        {
            formLabel.setText(forms[getRandom(17)]);
        }
        
        
    }//GEN-LAST:event_randFormButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private Integer genRandNum (int maxNum)
    {
        int number = rand.nextInt(maxNum);
        return number;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> formCombo;
    private javax.swing.JLabel formLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton randFormButton;
    // End of variables declaration//GEN-END:variables
}
